nelmio_api_doc:
    documentation:
        info:
            title: IFSP - Confirmação de Presença
            description: Aplicação para confirmações de presenças de alunos em enventos educacionais.
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
            
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        #host_patterns: # document only routes with a host of the form api.*
        #    - ^api\.

    