twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        'templates/backend/template/adminkit': 'adminkit'
        'templates/backend': 'backend'
        'templates/frontend': 'frontend'
    globals:
        backend_version: '%app.backend_version%'
        backend_name: '%app.backend_name%'
        backend_lang: 'pt-br'
        site_author: 'Grupo 10'

when@test:
    twig:
        strict_variables: true
