# config/routes.yaml
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
    
api_login_check:
    path: /api/auth

jwt_auth:
    path: /api/auth

jwt_refresh:
    path: /auth/refresh

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
